CREATE PROCEDURE Alocacao()
AS $$
DECLARE
alocar INT;
f VARCHAR(100);
cursor CURSOR FOR SELECT nome, count(nome) as alocar FROM filme f, (SELECT COD_FILME FROM EXEMPLAR E, LOCACAO L WHERE L.COD_EXEMPLAR = E.COD_EXEMPLAR) a WHERE f.COD_FILME = a.COD_FILME GROUP BY f.nome ORDER BY f.nome ASC;
BEGIN
OPEN cursor;
LOOP
FETCH NEXT FROM cursor INTO f, alocar;
EXIT WHEN NOT FOUND;
RAISE INFO '% - %', f, alocar;
END LOOP;
CLOSE cursor;
END; 
$$ LANGUAGE plpgsql;
CALL Alocacao();
